/**
 * ⚠️  CERBER TEMPLATE (NOT SOURCE OF TRUTH)
 *
 * This file is a starting point. Edit it to match YOUR architecture.
 * The source of truth is CERBER.md.
 *
 * Generated by: npx cerber init
 * Project: cerber-e2e-demo
 *
 * See: https://github.com/Agaslez/cerber-core#guardian-configuration
 */

export const BACKEND_SCHEMA = {
  version: "1.0.0",

  // Your architecture rules (customize)
  rules: [],

  // Patterns that should never appear in your code
  forbiddenPatterns: [
    {
      pattern: "password\\s*=\\s*['\"][^'\"]+['\"]",
      flags: "i",
      name: "Hardcoded passwords",
      severity: "error"
    },
    {
      pattern: "api[_-]?key\\s*=\\s*['\"][^'\"]+['\"]",
      flags: "i",
      name: "Hardcoded API keys",
      severity: "error"
    }
  ]
};

export default BACKEND_SCHEMA;

/**
 * Example patterns you might want to add:
 * 
 * - SQL injection risks:
 *   pattern: "\\$\\{.*?\\}.*?WHERE",
 *   message: "Possible SQL injection via template literals"
 * 
 * - Secrets in env files:
 *   pattern: "(SECRET|PASSWORD|API_KEY)\\s*=\\s*['\"][^'\"]+['\"]",
 *   locations: [".env", ".env.local"],
 *   message: "Hardcoded secrets"
 * 
 * Full examples:
 * - node_modules/cerber-core/examples/backend-schema.ts
 * - node_modules/cerber-core/examples/frontend-schema.ts
 */
